server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.161.205:3306/db2024?allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: byolio
    password: S=Aq#n5dIBh0
  profiles:
    active: dev   # 多环境加载到 dev/prod, 不写就是默认default的配置

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.byolio.cloud.entities
  configuration:
    map-underscore-to-camel-case: true